### PR TITLE
Speedups

### PR DESCRIPTION
**Pull request by bnmajor**

### CODE REVIEW

**Comment by bnmajor** [comment]
@manthey This addresses many of the core issues we initially discussed around excessive calls to save annotations. As we discussed previously I will make some follow-up PRs with additional speed/caching improvements.

**Comment by manthey** [comment]
This is a large improvement, though, as you noted, there are still other places to improve.  I do see extra writes to the config file, for instance.

Also, I note that when we switch chips in guided mode, we end up reading twice as many image tiles as we need -- we switch images and the tiles for the current screen location are queued, then we center the new chip and the tiles at that location are also read.

**Comment by bnmajor** [comment]
> This is a large improvement, though, as you noted, there are still other places to improve. I do see extra writes to the config file, for instance.
> 
> Also, I note that when we switch chips in guided mode, we end up reading twice as many image tiles as we need -- we switch images and the tiles for the current screen location are queued, then we center the new chip and the tiles at that location are also read.

I've pulled this comment out into a new issue along with a brief list of items I know need to be improved. I figure that we can continue to update that list as any of us encounter additional issues

**Comment by manthey** [comment]
> I've pulled this comment out into a new issue along with a brief list of items I know need to be improved. I figure that we can continue to update that list as any of us encounter additional issues

Great.  Go ahead and merge this.

**Pull request merged**
