### PR TITLE
Histomicsui config

### LINKED ISSUE #80: Resolve category mixing across projects

### PR DESCRIPTION
**Pull request by bnmajor**
Builds off of the work started in #36.

Fixes #80 and #22

### CODE REVIEW

**Comment by manthey** [comment]
When I run this with three categories, it adds a `default` category and everything is shifted by one category.  I started with a fresh directory without any config file.

**Comment by bnmajor** [comment]
> When I run this with three categories, it adds a `default` category and everything is shifted by one category. I started with a fresh directory without any config file.

Thank you! This should be corrected now.

**Comment by manthey** [comment]
When I show the predictions, the colors still seem messed up (but the labels on the chips look more correct).

**Comment by manthey** [comment]
I see a javascript error being thrown related to not having a default category.  I ran through two training epochs, then viewed the results in HistomicsUI, switch to a different project with different categories in HistomicsUI and switch back, then did a hard reload in the Guided Labeling UI, and get a console error in the `getAgreeChoice`.  I think this has to do with the default category bookkeeping, not the switching between different labelled projects.

**Comment by bnmajor** [comment]
> I see a javascript error being thrown related to not having a default category. I ran through two training epochs, then viewed the results in HistomicsUI, switch to a different project with different categories in HistomicsUI and switch back, then did a hard reload in the Guided Labeling UI, and get a console error in the `getAgreeChoice`. I think this has to do with the default category bookkeeping, not the switching between different labelled projects.

I believe that the remaining issues boiled down to the actual data not being updated correctly to reflect the order of categories read in from the config file... After the most recent change everything seems to be correct now. I do not see extra or missing categories in the navigation list or the predictions cards. Looking at annotations and predictions in both `ActiveLearning` as well as `HistomicsUI` all colors and labels appear correct (and both UI views look identical), and toggling between both I cannot produce any errors or cause any category co-mingling.

**Review by manthey — APPROVED** [review]
This works for me in several tests.  I do see a minor issue in that we seem to be handling key bindings twice after the initial labelling set up (the first time we see the chip view), but a reload fixes it.  However, this is such an improvement over what we have that I say we merge it and then sort any residual issues.

**Pull request merged**
